### ISSUE TITLE
Merchant inventory not showing up

### ISSUE THREAD

**Issue by jedi7000nathan** [xADDBx/ToyBox-Wrath#33]
### Description of the bug

This one is a bit of an old one happened a fair bit back in day but has recently returned with the latest patch, what happens is whenever I go to buy from a merchant their inventory does not show up and I get what is return to the map but no movement allowed, now going to the options menu does get me out of the bug but the merchent inventory still is borked

### Steps To Reproduce

In order to reproduce this bug its fairly simple talk with any merchant in the game and ask to see their goods.

### Expected Behavior

What I expected to happen was to go to the shop as normal with dialogue.

### Screenshots

![20240905161405_1](https://github.com/user-attachments/assets/233aad2b-7ea6-40c5-8acc-24e3638b07f4)

### Toybox Version

1.6.3 

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.4.0

### Anything else?

Just that this is an old bug that has shown up before in previous versions after new updates, it tends to happen after major patches I'm not sure why.

**Comment by xADDBx** [comment]
Seems like you told on discord this one fixed itself
